services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  CopenhagenUniversity\SiteWizard\:
    resource: '../Classes/*'

  CopenhagenUniversity\SiteWizard\Backend\Controller\SiteWizardController:
    tags:
      - backend.controller
